---
# docs: https://github.com/packit-service/packit/blob/master/docs/configuration.md
specfile_path: python-ogr.spec

upstream_package_name: ogr
downstream_package_name: python-ogr
upstream_project_url: https://github.com/packit-service/ogr

create_tarball_command: ["python3", "setup.py", "sdist", "--dist-dir", "."]
current_version_command: ["python3", "setup.py", "--version"]

jobs:

- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-stable
